export class Empleado {

  constructor(
    public Id_Empleado: number,
    public Empresa_Id: number,
    public NumEmpleado: string,
    public PrimerNombre: string,
    public SegundoNombre: string,
    public ApellidoPaterno: string,
    public ApellidoMaterno: string,
    public FechaNacimiento: string,
    public RFC: string,
    public CURP: string,
    public Calle: string,
    public NumExt: string,
    public NumInt: string,
    public Colonia: string,
    public Municipio: string,
    public Ciudad: string,
    public Estado: string,
    public CP: string,
    public Telefono: string,
    public Celular: string,
    public Correo: string,
    public FechaIngreso: string,
    public FechaFinContrato: string,
    public Estatus: string,
    public Puesto: string,
    public FrecuenciaPago: string,
    public IngresoNeto: string,
    public LimiteCredito: string,
    public TotalMontoSolicitado: string,
    public TotalAdeudo: string,
    public Usuario_Id: number,
    public FechaCreacion: string,
    public UsuarioMod_Id: number,
    public FechaMod: string,

  ) { }

}
