export class Empleado {

  constructor(
    public Id_Empresa: number,
    public Empresa: string,
    public NumEmpleado: string,
    public Id_Empleado: number,
    public RFC: string,
    public CURP: string,
    public PrimerNombre: string,
    public SegundoNombre: string,
    public ApellidoPaterno: string,
    public ApellidoMaterno: string,
    public FechaNacimiento: string,
    public Calle: string,
    public NumExt: string,
    public NumInt: string,
    public Id_Estado: number,
    public Estado: string,
    public Id_Municipio: number,
    public Municipio: string,
    public Id_Colonia: number,
    public Colonia: string,
    public CP: string,
    public TelefonoFijo: string,
    public TelefonoCelular: string,
    public Correo: string,
    public Puesto: string,
    public FechaIngreso: string,
    public IngresoNeto: number,
    public Id_TipoNomina: number,
    public TipoNomina: string,
    public FechaCorteNomina: string,
    public MontoMaximo: number,
    public SaldoDisponible: number,
    public FechaVencimientoContrato: string,
    public CargaMasiva: string,
    public Tarjeta: string,
    public MotivoBaja: string,
    public FrecuenciaPago: string,
    public FrecuenciaPago_Id: string,
    public Estatus_Id: string

  ) { }

}
