
export class Visita {
    constructor(
        public Id_Visita?: number,
        public Cliente_Id?: number,
        public NombreCliente?: string,
        public Folio?: string,
        public Usuario_Id?: number,
        public Usuario?: string,
        public TipoVisita_Id?: number,
        public TipoVisita?: string,
        public CP?: string,
        public Colonia?: string,
        public Municipio?: string,
        public Estado?: string,
        public Calle?: string,
        public NumExterior?: number,
        public NumInterior?: number,
        public EntreCalles?: string,
        public ReferenciaDomicilio?: string,
        public TipoInmueble?: string,
        public AniosResidencia?: number,
        public MesesResidencia?: number,
        public TelefonoCelular?: string,
        public TelefonoOficina?: string,
        public NombreEmpresa?: string,
        public JefeInmediato?: string,
        public Departamento?: string,
        public Puesto?: string,
        public Giro?: string,
        public TipoLocal?: string,
        public DescripcionLocal?: string,
        public DescripcionActividad?: string,
        public NombreArrendador?: string,
        public TelefonoArrendador?: string,
        public Especificaciones?: string,
        public FechaVisitaCreada?: Date,
        public FechaVisitaConcluida?: Date,
        public Latitud?: number,
        public Longitud?: number,
        public Estatus?: number
    ) { }
}
